# Generated by Django 4.0.2 on 2022-02-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FE', 'front-end'), ('BE', 'back-end'), ('IOS', 'IOS'), ('AND', 'Android')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('bug', 'bug'), ('task', 'task'), ('improvement', 'improvement')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50)),
                ('status', models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('done', 'done')], max_length=50)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracking.project')),
            ],
        ),
    ]
