# Generated by Django 4.0.2 on 2022-02-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
