# Generated by Django 4.0.2 on 2022-02-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0002_remove_project_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='project_id',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracking.issue')),
            ],
        ),
    ]
