# Generated by Django 4.0.2 on 2022-02-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0003_rename_project_issue_project_id_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
