# Generated by Django 4.0.2 on 2022-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0007_alter_comment_author_user_id_alter_comment_issue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('author', 'author'), ('contributor', 'contributor')], default='', max_length=50),
        ),
    ]
