# Generated by Django 4.0.2 on 2022-02-09 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracking', '0008_alter_contributors_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', through='issue_tracking.Contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
