# Generated by Django 4.0.2 on 2022-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0009_rename_project_id_contributors_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author_user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('front-end', 'front-end'), ('back-end', 'back-end'), ('IOS', 'IOS'), ('android', 'android')], max_length=20),
        ),
    ]
