# Generated by Django 4.0.2 on 2022-02-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0010_remove_comment_author_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_id',
        ),
        migrations.AddField(
            model_name='issue',
            name='projects',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='issue_tracking.project'),
            preserve_default=False,
        ),
    ]
